from django.urls import path

from .views import (
    ActivityCollectionView,
    AvailableCoursesView,
    ActivityDetailView,
    AuditLogCollectionView,
    AuditLogDetailView,
    CourseCollectionView,
    CourseDetailView,
    CourseHistoryView,
    CourseHostAvailabilityView,
    CourseHostCollectionView,
    CourseHostDetailView,
    CourseHostFormatsView,
    CourseHostInstallView,
    CourseHostRetireView,
    CourseHostVerifyView,
    CoursePackageZipInstallView,
    CourseManifestView,
    CourseUninstallView,
    HostCourseListView,
    HostInstalledCoursesView,
    StudentCourseProgressView,
    StudentCoursesView,
    StudentHostCatalogView,
    CoursePackageImportView,
    CoursePackageInspectView,
    CourseRollbackView,
    CourseVersionCollectionView,
    CourseVersionActivateView,
    CourseVersionDetailView,
    CourseVersionListView,
    CourseVersionPackageView,
    CurriculumFrameworkCollectionView,
    CurriculumFrameworkDetailView,
    EnrollmentCollectionView,
    EnrollmentDetailView,
    LearningResourceCollectionView,
    LearningResourceDetailView,
    LessonCollectionView,
    LessonDetailView,
    LessonItemCollectionView,
    LessonItemDetailView,
    QuizAnswerView,
    QuizFinishView,
    QuizOptionCollectionView,
    QuizOptionDetailView,
    QuizProgressView,
    QuizPublicView,
    QuizQuestionCollectionView,
    QuizQuestionDetailView,
    QuizResultDetailView,
    QuizResultsView,
    QuizStartView,
    SectionCollectionView,
    SectionDetailView,
)


from .views_contenido import (
    ContenidoCatalogoView,
    ContenidoElementoView,
    ContenidoEstadoView,
    ContenidoMostrarView,
    ContenidoTaxonomiaView,
    ExamenComprobarView,
    ExamenMontarView,
    LeccionMaterialView,
    MaterialDetailView,
    RepartoCerrarView,
    RepartoView,
    StudentContenidoView,
)

urlpatterns = [
    # ── Integración con AVACOM-Contenido ─────────────────────────────────────
    # El componente vive en el mismo equipo y solo habla por 127.0.0.1 con este
    # backend. Ninguna tableta lo alcanza: piden aquí y aquí se decide.
    path("contenido/estado/", ContenidoEstadoView.as_view(), name="contenido-estado"),
    path("contenido/catalogo/", ContenidoCatalogoView.as_view(), name="contenido-catalogo"),
    path("contenido/taxonomia/", ContenidoTaxonomiaView.as_view(), name="contenido-taxonomia"),
    path("contenido/elemento/<path:referencia>/", ContenidoElementoView.as_view(), name="contenido-elemento"),
    path("contenido/mostrar/", ContenidoMostrarView.as_view(), name="contenido-mostrar"),
    path("contenido/reparto/", RepartoView.as_view(), name="contenido-reparto"),
    path("contenido/reparto/<str:pk>/cerrar/", RepartoCerrarView.as_view(), name="contenido-reparto-cerrar"),
    path("contenido/examen/montar/", ExamenMontarView.as_view(), name="contenido-examen-montar"),
    path("contenido/examen/comprobar/", ExamenComprobarView.as_view(), name="contenido-examen-comprobar"),
    path("lecciones/<str:leccion_id>/materiales/", LeccionMaterialView.as_view(), name="leccion-materiales"),
    path("materiales/<str:pk>/", MaterialDetailView.as_view(), name="material-detalle"),
    path("students/<str:persona_id>/contenido/", StudentContenidoView.as_view(), name="student-contenido"),
    path("curriculum-frameworks/", CurriculumFrameworkCollectionView.as_view()),
    path("curriculum-frameworks/<str:pk>/", CurriculumFrameworkDetailView.as_view()),
    path("courses/", CourseCollectionView.as_view(), name="courses"),

    # ── API del spec · §19 ────────────────────────────────────────────────
    # Rutas con los nombres que pide el spec. No hay DELETE de curso a
    # proposito: desinstalar contenido no es borrar lo academico.
    path("courses/available/", AvailableCoursesView.as_view(), name="courses-available"),
    path("courses/history/", CourseHistoryView.as_view(), name="courses-history"),
    path("course-packages/install/", CoursePackageZipInstallView.as_view(), name="package-zip-install"),
    path("courses/<str:course_id>/uninstall/", CourseUninstallView.as_view(), name="course-uninstall"),
    path("students/<str:student_id>/courses/", StudentCoursesView.as_view(), name="student-courses"),
    path("students/<str:student_id>/courses/<str:course_id>/progress/", StudentCourseProgressView.as_view(), name="student-course-progress"),
    path("courses/<str:pk>/", CourseDetailView.as_view(), name="course-detail"),
    path("course-versions/", CourseVersionCollectionView.as_view()),
    path("course-versions/<str:pk>/", CourseVersionDetailView.as_view()),
    path("enrollments/", EnrollmentCollectionView.as_view(), name="enrollments"),
    path("enrollments/<str:pk>/", EnrollmentDetailView.as_view()),
    path("sections/", SectionCollectionView.as_view(), name="sections"),
    path("sections/<str:pk>/", SectionDetailView.as_view()),
    path("lessons/", LessonCollectionView.as_view(), name="lessons"),
    path("lessons/<str:pk>/", LessonDetailView.as_view()),
    path("lesson-items/", LessonItemCollectionView.as_view(), name="lesson-items"),
    path("lesson-items/<str:pk>/", LessonItemDetailView.as_view()),
    path("learning-resources/", LearningResourceCollectionView.as_view()),
    path("learning-resources/<str:pk>/", LearningResourceDetailView.as_view()),
    path("activities/", ActivityCollectionView.as_view()),
    path("activities/<str:pk>/", ActivityDetailView.as_view()),
    path("audit-logs/", AuditLogCollectionView.as_view()),
    path("audit-logs/<str:pk>/", AuditLogDetailView.as_view()),
    path("quiz-questions/", QuizQuestionCollectionView.as_view()),
    path("quiz-questions/<str:pk>/", QuizQuestionDetailView.as_view()),
    path("quiz-options/", QuizOptionCollectionView.as_view()),
    path("quiz-options/<str:pk>/", QuizOptionDetailView.as_view()),
    path("quizzes/<str:activity_id>/", QuizPublicView.as_view(), name="quiz-public"),
    path("quiz-attempts/start/", QuizStartView.as_view(), name="quiz-start"),
    path("quiz-attempts/progress/", QuizProgressView.as_view(), name="quiz-progress"),
    path("quiz-attempts/answer/", QuizAnswerView.as_view(), name="quiz-answer"),
    path("quiz-attempts/finish/", QuizFinishView.as_view(), name="quiz-finish"),
    path("quiz-results/", QuizResultsView.as_view(), name="quiz-results"),
    path("quiz-results/<str:attempt_id>/", QuizResultDetailView.as_view(), name="quiz-result-detail"),

    # ── Catálogo versionado ──────────────────────────────────────────────
    # El manifiesto dice QUÉ versión debería tener el cliente; el paquete trae
    # el contenido. Activar y revertir son operaciones del servidor porque la
    # decisión de qué se publica es académica, no del dispositivo.
    path("courses/<str:course_id>/manifest/", CourseManifestView.as_view(), name="course-manifest"),
    path("courses/<str:course_id>/versions/", CourseVersionListView.as_view(), name="course-versions"),
    path("courses/<str:course_id>/rollback/", CourseRollbackView.as_view(), name="course-rollback"),
    path("course-versions/<str:version_id>/package/", CourseVersionPackageView.as_view(), name="course-version-package"),
    path("course-versions/<str:version_id>/activate/", CourseVersionActivateView.as_view(), name="course-version-activate"),

    # Importar un paquete desde la OPS: primero se inspecciona, luego se confirma.
    path("course-packages/inspect/", CoursePackageInspectView.as_view(), name="package-inspect"),
    path("course-packages/import/", CoursePackageImportView.as_view(), name="package-import"),

    # ── Presencia fisica en un host (m05_curso_host) ─────────────────────
    # Responde que cursos estan instalados en esta OPS y cuales se quitaron.
    # Desinstalar apaga banderas y sella fechas: nunca borra el curso ni las
    # inscripciones ni las notas.
    path("course-hosts/", CourseHostCollectionView.as_view(), name="course-hosts"),
    path("course-hosts/formats/", CourseHostFormatsView.as_view(), name="course-host-formats"),
    path("course-hosts/install/", CourseHostInstallView.as_view(), name="course-host-install"),
    path("course-hosts/retire/", CourseHostRetireView.as_view(), name="course-host-retire"),
    path("course-hosts/availability/", CourseHostAvailabilityView.as_view(), name="course-host-availability"),
    path("course-hosts/verify/", CourseHostVerifyView.as_view(), name="course-host-verify"),
    path("course-hosts/<str:pk>/", CourseHostDetailView.as_view(), name="course-host-detail"),
    path("hosts/<str:host_id>/courses/", HostCourseListView.as_view(), name="host-courses"),
    path("hosts/<str:host_id>/installed/", HostInstalledCoursesView.as_view(), name="host-installed"),
    path("students/<str:persona_id>/host-catalog/", StudentHostCatalogView.as_view(), name="student-host-catalog"),
]
