from django.urls import path

from .views import (
    ActivityCollectionView,
    ActivityDetailView,
    AuditLogCollectionView,
    AuditLogDetailView,
    CourseCollectionView,
    CourseDetailView,
    CourseManifestView,
    CoursePackageImportView,
    CoursePackageInspectView,
    CourseRollbackView,
    CourseVersionCollectionView,
    CourseVersionActivateView,
    CourseVersionDetailView,
    CourseVersionListView,
    CourseVersionPackageView,
    CurriculumFrameworkCollectionView,
    CurriculumFrameworkDetailView,
    EnrollmentCollectionView,
    EnrollmentDetailView,
    LearningResourceCollectionView,
    LearningResourceDetailView,
    LessonCollectionView,
    LessonDetailView,
    LessonItemCollectionView,
    LessonItemDetailView,
    QuizAnswerView,
    QuizFinishView,
    QuizOptionCollectionView,
    QuizOptionDetailView,
    QuizProgressView,
    QuizPublicView,
    QuizQuestionCollectionView,
    QuizQuestionDetailView,
    QuizResultDetailView,
    QuizResultsView,
    QuizStartView,
    SectionCollectionView,
    SectionDetailView,
)


urlpatterns = [
    path("curriculum-frameworks/", CurriculumFrameworkCollectionView.as_view()),
    path("curriculum-frameworks/<str:pk>/", CurriculumFrameworkDetailView.as_view()),
    path("courses/", CourseCollectionView.as_view(), name="courses"),
    path("courses/<str:pk>/", CourseDetailView.as_view(), name="course-detail"),
    path("course-versions/", CourseVersionCollectionView.as_view()),
    path("course-versions/<str:pk>/", CourseVersionDetailView.as_view()),
    path("enrollments/", EnrollmentCollectionView.as_view(), name="enrollments"),
    path("enrollments/<str:pk>/", EnrollmentDetailView.as_view()),
    path("sections/", SectionCollectionView.as_view(), name="sections"),
    path("sections/<str:pk>/", SectionDetailView.as_view()),
    path("lessons/", LessonCollectionView.as_view(), name="lessons"),
    path("lessons/<str:pk>/", LessonDetailView.as_view()),
    path("lesson-items/", LessonItemCollectionView.as_view(), name="lesson-items"),
    path("lesson-items/<str:pk>/", LessonItemDetailView.as_view()),
    path("learning-resources/", LearningResourceCollectionView.as_view()),
    path("learning-resources/<str:pk>/", LearningResourceDetailView.as_view()),
    path("activities/", ActivityCollectionView.as_view()),
    path("activities/<str:pk>/", ActivityDetailView.as_view()),
    path("audit-logs/", AuditLogCollectionView.as_view()),
    path("audit-logs/<str:pk>/", AuditLogDetailView.as_view()),
    path("quiz-questions/", QuizQuestionCollectionView.as_view()),
    path("quiz-questions/<str:pk>/", QuizQuestionDetailView.as_view()),
    path("quiz-options/", QuizOptionCollectionView.as_view()),
    path("quiz-options/<str:pk>/", QuizOptionDetailView.as_view()),
    path("quizzes/<str:activity_id>/", QuizPublicView.as_view(), name="quiz-public"),
    path("quiz-attempts/start/", QuizStartView.as_view(), name="quiz-start"),
    path("quiz-attempts/progress/", QuizProgressView.as_view(), name="quiz-progress"),
    path("quiz-attempts/answer/", QuizAnswerView.as_view(), name="quiz-answer"),
    path("quiz-attempts/finish/", QuizFinishView.as_view(), name="quiz-finish"),
    path("quiz-results/", QuizResultsView.as_view(), name="quiz-results"),
    path("quiz-results/<str:attempt_id>/", QuizResultDetailView.as_view(), name="quiz-result-detail"),

    # ── Catálogo versionado ──────────────────────────────────────────────
    # El manifiesto dice QUÉ versión debería tener el cliente; el paquete trae
    # el contenido. Activar y revertir son operaciones del servidor porque la
    # decisión de qué se publica es académica, no del dispositivo.
    path("courses/<str:course_id>/manifest/", CourseManifestView.as_view(), name="course-manifest"),
    path("courses/<str:course_id>/versions/", CourseVersionListView.as_view(), name="course-versions"),
    path("courses/<str:course_id>/rollback/", CourseRollbackView.as_view(), name="course-rollback"),
    path("course-versions/<str:version_id>/package/", CourseVersionPackageView.as_view(), name="course-version-package"),
    path("course-versions/<str:version_id>/activate/", CourseVersionActivateView.as_view(), name="course-version-activate"),

    # Importar un paquete desde la OPS: primero se inspecciona, luego se confirma.
    path("course-packages/inspect/", CoursePackageInspectView.as_view(), name="package-inspect"),
    path("course-packages/import/", CoursePackageImportView.as_view(), name="package-import"),
]
