# Generated by Django 5.2.3 on 2026-08-27 22:52

import django.core.validators
import django.db.models.deletion
import exams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(default=exams.models.new_document_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('docente_id', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pruebas', 'Pruebas'), ('habilitado', 'Habilitado'), ('retirado', 'Retirado')], default='borrador', max_length=16)),
                ('idioma', models.CharField(default='es', max_length=8)),
                ('retirado_en', models.BigIntegerField(blank=True, null=True)),
                ('creado_en', models.BigIntegerField(default=exams.models.now_ms)),
                ('creado_por', models.CharField(blank=True, max_length=64, null=True)),
                ('secuencia', models.BigIntegerField(default=exams.models.sequence_value)),
            ],
            options={
                'db_table': 'm05_curso',
                'ordering': ['-creado_en', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumFramework',
            fields=[
                ('clave', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=160)),
                ('pais', models.CharField(blank=True, max_length=8, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.BigIntegerField(default=exams.models.now_ms)),
                ('creado_por', models.CharField(blank=True, max_length=64, null=True)),
                ('secuencia', models.BigIntegerField(default=exams.models.sequence_value)),
            ],
            options={
                'db_table': 'm05_marco_curricular',
                'ordering': ['orden', 'clave'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.CharField(default=exams.models.new_document_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('competency_framework', models.CharField(blank=True, max_length=64, null=True)),
                ('learning_outcome', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('attitudes_values', models.TextField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('estado', models.CharField(choices=[('draft', 'Borrador'), ('publicado', 'Publicado'), ('cerrado', 'Cerrado')], default='draft', max_length=16)),
                ('creado_en', models.BigIntegerField(default=exams.models.now_ms)),
                ('creado_por', models.CharField(blank=True, max_length=64, null=True)),
                ('secuencia', models.BigIntegerField(default=exams.models.sequence_value)),
            ],
            options={
                'db_table': 'm05_leccion',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.CharField(default=exams.models.new_document_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activity_type', models.CharField(choices=[('quiz', 'Quiz'), ('assignment', 'Tarea'), ('exam', 'Examen')], max_length=16)),
                ('submission_type', models.CharField(choices=[('quiz', 'Quiz'), ('file', 'Archivo'), ('none', 'Sin entrega')], max_length=16)),
                ('grading_type', models.CharField(choices=[('automatic', 'Automática'), ('teacher', 'Docente'), ('mixed', 'Mixta')], max_length=16)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('autor_id', models.CharField(blank=True, max_length=64, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('retirada', 'Retirada')], default='activa', max_length=16)),
                ('creado_en', models.BigIntegerField(default=exams.models.now_ms)),
                ('creado_por', models.CharField(blank=True, max_length=64, null=True)),
                ('secuencia', models.BigIntegerField(default=exams.models.sequence_value)),
            ],
            options={
                'db_table': 'm10_actividad',
                'ordering': ['titulo'],
                'indexes': [models.Index(fields=['activity_type', 'estado'], name='ix_m10_actividad_tipo')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.CharField(default=exams.models.new_document_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('actor_id', models.CharField(blank=True, max_length=64, null=True)),
                ('accion', models.CharField(max_length=120)),
                ('objeto_tabla', models.CharField(max_length=120)),
                ('objeto_id', models.CharField(max_length=64)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('resultado', models.CharField(choices=[('ok', 'OK'), ('denegado', 'Denegado'), ('error', 'Error')], default='ok', max_length=16)),
                ('ocurrido_en', models.BigIntegerField(default=exams.models.now_ms)),
                ('secuencia', models.BigIntegerField(default=exams.models.sequence_value)),
            ],
            options={
                'db_table': 'm19_auditoria',
                'ordering': ['-ocurrido_en'],
                'indexes': [models.Index(fields=['actor_id', 'ocurrido_en'], name='ix_m19_aud_actor'), models.Index(fields=['objeto_tabla', 'objeto_id', 'ocurrido_en'], name='ix_m19_aud_objeto')],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.CharField(default=exams.models.new_document_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('persona_id', models.CharField(max_length=64)),
                ('alta', models.BigIntegerField(default=exams.models.now_ms)),
                ('baja', models.BigIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('retirada', 'Retirada'), ('concluida', 'Concluida')], default='activa', max_length=16)),
                ('creado_en', models.BigIntegerField(default=exams.models.now_ms)),
                ('creado_por', models.CharField(blank=True, max_length=64, null=True)),
                ('secuencia', models.BigIntegerField(default=exams.models.sequence_value)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='exams.course')),
            ],
            options={
                'db_table': 'm05_curso_estudiante',
                'ordering': ['curso_id', 'creado_en'],
            },
        ),
        migrations.CreateModel(
            name='CourseVersion',
            fields=[
                ('id', models.CharField(default=exams.models.new_document_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('publicado_en', models.BigIntegerField(default=exams.models.now_ms)),
                ('publicado_por', models.CharField(max_length=64)),
                ('huella', models.CharField(max_length=64)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_en', models.BigIntegerField(default=exams.models.now_ms)),
                ('creado_por', models.CharField(blank=True, max_length=64, null=True)),
                ('secuencia', models.BigIntegerField(default=exams.models.sequence_value)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='exams.course')),
            ],
            options={
                'db_table': 'm05_curso_version',
                'ordering': ['curso_id', 'version'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='curriculum_framework',
            field=models.ForeignKey(db_column='curriculum_framework', on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='exams.curriculumframework'),
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.CharField(default=exams.models.new_document_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('content_type', models.CharField(choices=[('reading', 'Lectura'), ('video', 'Video'), ('audio', 'Audio')], max_length=16)),
                ('content_ref', models.CharField(max_length=500)),
                ('content_version', models.CharField(max_length=32)),
                ('content_huella', models.CharField(blank=True, max_length=64, null=True)),
                ('duracion_seg', models.PositiveIntegerField(blank=True, null=True)),
                ('autor_id', models.CharField(blank=True, max_length=64, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('retirado', 'Retirado')], default='activo', max_length=16)),
                ('creado_en', models.BigIntegerField(default=exams.models.now_ms)),
                ('creado_por', models.CharField(blank=True, max_length=64, null=True)),
                ('secuencia', models.BigIntegerField(default=exams.models.sequence_value)),
            ],
            options={
                'db_table': 'm05_recurso_aprendizaje',
                'ordering': ['titulo'],
                'indexes': [models.Index(fields=['content_ref', 'content_version'], name='ix_m05_recurso_ref'), models.Index(fields=['content_type', 'estado'], name='ix_m05_recurso_tipo')],
            },
        ),
        migrations.CreateModel(
            name='LessonItem',
            fields=[
                ('id', models.CharField(default=exams.models.new_document_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('orden', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('tipo', models.CharField(choices=[('contenido', 'Contenido'), ('actividad', 'Actividad'), ('referencia_externa', 'Referencia externa')], max_length=24)),
                ('elemento_ref', models.CharField(blank=True, max_length=500, null=True)),
                ('elemento_version', models.CharField(blank=True, max_length=32, null=True)),
                ('creado_en', models.BigIntegerField(default=exams.models.now_ms)),
                ('creado_por', models.CharField(blank=True, max_length=64, null=True)),
                ('secuencia', models.BigIntegerField(default=exams.models.sequence_value)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_items', to='exams.activity')),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='exams.lesson')),
                ('recurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_items', to='exams.learningresource')),
            ],
            options={
                'db_table': 'm05_leccion_item',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.CharField(default=exams.models.new_document_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('persona_id', models.CharField(max_length=64)),
                ('nombre_estudiante', models.CharField(max_length=250)),
                ('device_id', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(choices=[('en_progreso', 'En progreso'), ('finalizado', 'Finalizado')], default='en_progreso', max_length=16)),
                ('pregunta_actual', models.PositiveIntegerField(default=1)),
                ('puntaje', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_preguntas', models.PositiveIntegerField(default=0)),
                ('iniciado_en', models.BigIntegerField(default=exams.models.now_ms)),
                ('finalizado_en', models.BigIntegerField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='exams.activity')),
            ],
            options={
                'db_table': 'm10_quiz_intento',
                'ordering': ['-iniciado_en'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.CharField(default=exams.models.new_document_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=80)),
                ('texto', models.TextField()),
                ('orden', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('creado_en', models.BigIntegerField(default=exams.models.now_ms)),
                ('secuencia', models.BigIntegerField(default=exams.models.sequence_value)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='exams.activity')),
            ],
            options={
                'db_table': 'm10_quiz_pregunta',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.CharField(default=exams.models.new_document_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=400)),
                ('orden', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('es_correcta', models.BooleanField(default=False)),
                ('creado_en', models.BigIntegerField(default=exams.models.now_ms)),
                ('secuencia', models.BigIntegerField(default=exams.models.sequence_value)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='exams.quizquestion')),
            ],
            options={
                'db_table': 'm10_quiz_opcion',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.CharField(default=exams.models.new_document_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('es_correcta', models.BooleanField(default=False)),
                ('respondido_en', models.BigIntegerField(default=exams.models.now_ms)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='exams.quizattempt')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='exams.quizoption')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='exams.quizquestion')),
            ],
            options={
                'db_table': 'm10_quiz_respuesta',
                'ordering': ['pregunta__orden'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.CharField(default=exams.models.new_document_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('orden', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('creado_en', models.BigIntegerField(default=exams.models.now_ms)),
                ('creado_por', models.CharField(blank=True, max_length=64, null=True)),
                ('secuencia', models.BigIntegerField(default=exams.models.sequence_value)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='exams.course')),
            ],
            options={
                'db_table': 'm05_seccion',
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='exams.section'),
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
        migrations.DeleteModel(
            name='AnswerOption',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['persona_id', 'estado'], name='ix_m05_curso_est_persona'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(fields=('curso', 'persona_id'), name='ux_m05_curso_est'),
        ),
        migrations.AddConstraint(
            model_name='courseversion',
            constraint=models.UniqueConstraint(fields=('curso', 'version'), name='ux_m05_curso_version'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['docente_id', 'estado'], name='ix_m05_curso_docente'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['curriculum_framework'], name='ix_m05_curso_marco'),
        ),
        migrations.AddIndex(
            model_name='lessonitem',
            index=models.Index(fields=['actividad'], name='ix_m05_item_actividad'),
        ),
        migrations.AddIndex(
            model_name='lessonitem',
            index=models.Index(fields=['recurso'], name='ix_m05_item_recurso'),
        ),
        migrations.AddConstraint(
            model_name='lessonitem',
            constraint=models.UniqueConstraint(fields=('leccion', 'orden'), name='ux_m05_item_orden'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['actividad', 'estado'], name='ix_m10_quiz_intento_estado'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['persona_id', 'actividad'], name='ix_m10_quiz_intento_persona'),
        ),
        migrations.AddConstraint(
            model_name='quizquestion',
            constraint=models.UniqueConstraint(fields=('actividad', 'orden'), name='ux_m10_quiz_pregunta_orden'),
        ),
        migrations.AddConstraint(
            model_name='quizoption',
            constraint=models.UniqueConstraint(fields=('pregunta', 'orden'), name='ux_m10_quiz_opcion_orden'),
        ),
        migrations.AddConstraint(
            model_name='quizanswer',
            constraint=models.UniqueConstraint(fields=('intento', 'pregunta'), name='ux_m10_quiz_respuesta'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('curso', 'orden'), name='ux_m05_seccion_orden'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['estado'], name='ix_m05_leccion_estado'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['competency_framework'], name='ix_m05_leccion_marco'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('seccion', 'orden'), name='ux_m05_leccion_orden'),
        ),
    ]
