# Generated by Django 5.2.3 on 2026-08-27 23:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_course_curriculumframework_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
