# Generated by Django 5.2.3 on 2026-08-31 15:32

import django.db.models.deletion
import exams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_catalogo_versionado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseHost',
            fields=[
                ('id', models.CharField(default=exams.models.new_document_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('host_id', models.CharField(max_length=64)),
                ('scorm_manifest_id', models.CharField(blank=True, max_length=250, null=True)),
                ('scorm_organization_id', models.CharField(blank=True, max_length=250, null=True)),
                ('scorm_version', models.CharField(blank=True, max_length=32, null=True)),
                ('package_ref', models.CharField(blank=True, max_length=500, null=True)),
                ('package_huella', models.CharField(blank=True, max_length=64, null=True)),
                ('presente_local', models.BooleanField(default=True)),
                ('disponible_estudiante', models.BooleanField(default=False)),
                ('instalado_en', models.BigIntegerField(default=exams.models.now_ms)),
                ('retirado_en', models.BigIntegerField(blank=True, null=True)),
                ('verificado_en', models.BigIntegerField(blank=True, null=True)),
                ('creado_en', models.BigIntegerField(default=exams.models.now_ms)),
                ('creado_por', models.CharField(blank=True, max_length=64, null=True)),
                ('secuencia', models.BigIntegerField(default=exams.models.sequence_value)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosts', to='exams.course')),
                ('curso_version', models.ForeignKey(blank=True, db_column='curso_version_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hosts', to='exams.courseversion')),
            ],
            options={
                'db_table': 'm05_curso_host',
                'ordering': ['host_id', 'curso_id'],
                'indexes': [models.Index(fields=['host_id', 'presente_local'], name='ix_m05_ch_host'), models.Index(fields=['curso', 'presente_local'], name='ix_m05_ch_curso')],
                'constraints': [models.UniqueConstraint(fields=('host_id', 'curso'), name='ux_m05_ch_host_curso'), models.CheckConstraint(condition=models.Q(('presente_local', True), ('disponible_estudiante', False), _connector='OR'), name='ck_m05_ch_disponible_requiere_presente'), models.CheckConstraint(condition=models.Q(('presente_local', True), ('retirado_en__isnull', False), _connector='OR'), name='ck_m05_ch_retirado_con_fecha')],
            },
        ),
    ]
