# Generated by Django 5.2.3 on 2026-08-31 16:14

import django.core.validators
import django.db.models.deletion
import exams.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_host_neutral_scorm_cmi5'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.CharField(default=exams.models.new_document_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('persona_id', models.CharField(max_length=64)),
                ('leccion_codigo', models.CharField(max_length=120)),
                ('leccion_titulo', models.CharField(blank=True, max_length=250)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('estado', models.CharField(choices=[('no_iniciada', 'No iniciada'), ('en_curso', 'En curso'), ('completada', 'Completada')], default='no_iniciada', max_length=16)),
                ('iniciado_en', models.BigIntegerField(default=exams.models.now_ms)),
                ('actualizado_en', models.BigIntegerField(default=exams.models.now_ms)),
                ('completado_en', models.BigIntegerField(blank=True, null=True)),
                ('creado_en', models.BigIntegerField(default=exams.models.now_ms)),
                ('creado_por', models.CharField(blank=True, max_length=64, null=True)),
                ('secuencia', models.BigIntegerField(default=exams.models.sequence_value)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progresos', to='exams.course')),
            ],
            options={
                'db_table': 'm05_progreso_leccion',
                'ordering': ['curso_id', 'persona_id', 'leccion_codigo'],
                'indexes': [models.Index(fields=['persona_id', 'curso'], name='ix_m05_prog_persona')],
                'constraints': [models.UniqueConstraint(fields=('curso', 'persona_id', 'leccion_codigo'), name='ux_m05_prog_leccion'), models.CheckConstraint(condition=models.Q(('porcentaje__gte', 0), ('porcentaje__lte', 100)), name='ck_m05_prog_porcentaje'), models.CheckConstraint(condition=models.Q(models.Q(('estado', 'completada'), _negated=True), models.Q(('porcentaje', 100), ('completado_en__isnull', False)), _connector='OR'), name='ck_m05_prog_completada')],
            },
        ),
    ]
