# Generated by Django 5.2.3 on 2026-08-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_progreso_leccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursehost',
            name='formato_contenido',
            field=models.CharField(choices=[('scorm_12', 'SCORM 1.2'), ('scorm_2004', 'SCORM 2004'), ('cmi5', 'cmi5'), ('avacom_v1', 'AVACOM course package v1'), ('avacom_contenido', 'AVACOM-Contenido')], default='avacom_v1', max_length=32),
        ),
    ]
