# Generated by Django 5.2.3 on 2026-09-01 17:03

import django.core.validators
import django.db.models.deletion
import exams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_formato_avacom_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenPregunta',
            fields=[
                ('id', models.CharField(default=exams.models.new_document_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('persona_id', models.CharField(max_length=64)),
                ('pregunta_ref', models.CharField(max_length=200)),
                ('elemento_ref', models.CharField(max_length=200)),
                ('version_elemento', models.CharField(blank=True, max_length=32, null=True)),
                ('orden', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('creado_en', models.BigIntegerField(default=exams.models.now_ms)),
                ('creado_por', models.CharField(blank=True, max_length=64, null=True)),
                ('secuencia', models.BigIntegerField(default=exams.models.sequence_value)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preguntas_referenciadas', to='exams.activity')),
            ],
            options={
                'db_table': 'm05_examen_pregunta',
                'ordering': ['actividad_id', 'persona_id', 'orden'],
                'indexes': [models.Index(fields=['persona_id'], name='ix_m05_ep_persona'), models.Index(fields=['elemento_ref'], name='ix_m05_ep_elemento')],
                'constraints': [models.UniqueConstraint(fields=('actividad', 'persona_id', 'pregunta_ref'), name='ux_m05_ep_actividad_persona_pregunta'), models.UniqueConstraint(fields=('actividad', 'persona_id', 'orden'), name='ux_m05_ep_actividad_persona_orden')],
            },
        ),
        migrations.CreateModel(
            name='RepartoActivo',
            fields=[
                ('id', models.CharField(default=exams.models.new_document_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('host_id', models.CharField(max_length=64)),
                ('sesion_clase_id', models.CharField(max_length=64)),
                ('grupo_id', models.CharField(blank=True, max_length=64, null=True)),
                ('elemento_ref', models.CharField(max_length=200)),
                ('version_elemento', models.CharField(blank=True, max_length=32, null=True)),
                ('tipo', models.CharField(blank=True, max_length=32, null=True)),
                ('abierto_en', models.BigIntegerField(default=exams.models.now_ms)),
                ('cerrado_en', models.BigIntegerField(blank=True, null=True)),
                ('abierto_por', models.CharField(blank=True, max_length=64, null=True)),
                ('creado_en', models.BigIntegerField(default=exams.models.now_ms)),
                ('creado_por', models.CharField(blank=True, max_length=64, null=True)),
                ('secuencia', models.BigIntegerField(default=exams.models.sequence_value)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repartos', to='exams.course')),
            ],
            options={
                'db_table': 'm05_reparto_activo',
                'ordering': ['-abierto_en'],
                'indexes': [models.Index(fields=['host_id', 'cerrado_en'], name='ix_m05_ra_host'), models.Index(fields=['elemento_ref'], name='ix_m05_ra_elemento')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cerrado_en__isnull', True)), fields=('host_id', 'sesion_clase_id', 'elemento_ref'), name='ux_m05_ra_abierto'), models.CheckConstraint(condition=models.Q(('cerrado_en__isnull', True), ('cerrado_en__gte', models.F('abierto_en')), _connector='OR'), name='ck_m05_ra_cierre_posterior')],
            },
        ),
        migrations.CreateModel(
            name='UnidadMaterial',
            fields=[
                ('id', models.CharField(default=exams.models.new_document_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('elemento_ref', models.CharField(max_length=200)),
                ('version_elemento', models.CharField(max_length=32)),
                ('taxonomia_ref', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo', models.CharField(blank=True, max_length=32, null=True)),
                ('orden', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('creado_en', models.BigIntegerField(default=exams.models.now_ms)),
                ('creado_por', models.CharField(blank=True, max_length=64, null=True)),
                ('secuencia', models.BigIntegerField(default=exams.models.sequence_value)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiales', to='exams.lesson')),
            ],
            options={
                'db_table': 'm05_unidad_material',
                'ordering': ['leccion_id', 'orden'],
                'indexes': [models.Index(fields=['elemento_ref'], name='ix_m05_um_elemento'), models.Index(fields=['taxonomia_ref'], name='ix_m05_um_taxonomia')],
                'constraints': [models.UniqueConstraint(fields=('leccion', 'elemento_ref', 'version_elemento'), name='ux_m05_um_leccion_elemento')],
            },
        ),
    ]
