# Generated by Django 5.2.3 on 2026-09-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_integracion_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmaterial',
            name='desaparecido_en',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidadmaterial',
            name='disponible_ultima_revision',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unidadmaterial',
            name='revisado_en',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='unidadmaterial',
            index=models.Index(fields=['disponible_ultima_revision'], name='ix_m05_um_disp'),
        ),
        migrations.AddConstraint(
            model_name='unidadmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('disponible_ultima_revision', True), ('desaparecido_en__isnull', False), _connector='OR'), name='ck_m05_um_ausencia_con_fecha'),
        ),
    ]
